/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ChatRoomInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createRoom"
      | "editMessage"
      | "getEncryptedMessage"
      | "getMessageMetadata"
      | "getRoom"
      | "getRoomMessageCount"
      | "getUserNickname"
      | "isUserRegistered"
      | "messages"
      | "registerUser"
      | "roomMessageCounts"
      | "rooms"
      | "sendMessage"
      | "totalMessages"
      | "totalRooms"
      | "updateNickname"
      | "userProfiles"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MessageEdited"
      | "MessageSent"
      | "NicknameUpdated"
      | "RoomCreated"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createRoom",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "editMessage",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedMessage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageMetadata",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoom",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoomMessageCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserNickname",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isUserRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "messages",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "roomMessageCounts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "rooms", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "sendMessage",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalMessages",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRooms",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateNickname",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userProfiles",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "createRoom", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "editMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRoom", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoomMessageCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserNickname",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUserRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "messages", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "roomMessageCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rooms", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sendMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalRooms", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateNickname",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userProfiles",
    data: BytesLike
  ): Result;
}

export namespace MessageEditedEvent {
  export type InputTuple = [
    roomId: BigNumberish,
    messageId: BigNumberish,
    sender: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    roomId: bigint,
    messageId: bigint,
    sender: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    roomId: bigint;
    messageId: bigint;
    sender: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageSentEvent {
  export type InputTuple = [
    roomId: BigNumberish,
    messageId: BigNumberish,
    sender: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    roomId: bigint,
    messageId: bigint,
    sender: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    roomId: bigint;
    messageId: bigint;
    sender: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NicknameUpdatedEvent {
  export type InputTuple = [user: AddressLike, newNickname: string];
  export type OutputTuple = [user: string, newNickname: string];
  export interface OutputObject {
    user: string;
    newNickname: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoomCreatedEvent {
  export type InputTuple = [
    roomId: BigNumberish,
    name: string,
    creator: AddressLike
  ];
  export type OutputTuple = [roomId: bigint, name: string, creator: string];
  export interface OutputObject {
    roomId: bigint;
    name: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [user: AddressLike, nickname: string];
  export type OutputTuple = [user: string, nickname: string];
  export interface OutputObject {
    user: string;
    nickname: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ChatRoom extends BaseContract {
  connect(runner?: ContractRunner | null): ChatRoom;
  waitForDeployment(): Promise<this>;

  interface: ChatRoomInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createRoom: TypedContractMethod<
    [name: string, description: string],
    [bigint],
    "nonpayable"
  >;

  editMessage: TypedContractMethod<
    [
      roomId: BigNumberish,
      messageId: BigNumberish,
      newEncryptedContent: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEncryptedMessage: TypedContractMethod<
    [roomId: BigNumberish, messageId: BigNumberish],
    [string],
    "view"
  >;

  getMessageMetadata: TypedContractMethod<
    [roomId: BigNumberish, messageId: BigNumberish],
    [
      [string, bigint, boolean, bigint] & {
        sender: string;
        timestamp: bigint;
        edited: boolean;
        editTimestamp: bigint;
      }
    ],
    "view"
  >;

  getRoom: TypedContractMethod<
    [roomId: BigNumberish],
    [
      [string, string, string, bigint] & {
        name: string;
        description: string;
        creator: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getRoomMessageCount: TypedContractMethod<
    [roomId: BigNumberish],
    [bigint],
    "view"
  >;

  getUserNickname: TypedContractMethod<[user: AddressLike], [string], "view">;

  isUserRegistered: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  messages: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, string, bigint, bigint, boolean, bigint] & {
        sender: string;
        roomId: bigint;
        encryptedContent: string;
        timestamp: bigint;
        messageId: bigint;
        edited: boolean;
        editTimestamp: bigint;
      }
    ],
    "view"
  >;

  registerUser: TypedContractMethod<[nickname: string], [void], "nonpayable">;

  roomMessageCounts: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  rooms: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, boolean] & {
        name: string;
        description: string;
        creator: string;
        createdAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  sendMessage: TypedContractMethod<
    [roomId: BigNumberish, encryptedContent: BytesLike],
    [bigint],
    "nonpayable"
  >;

  totalMessages: TypedContractMethod<[], [bigint], "view">;

  totalRooms: TypedContractMethod<[], [bigint], "view">;

  updateNickname: TypedContractMethod<
    [newNickname: string],
    [void],
    "nonpayable"
  >;

  userProfiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint] & {
        nickname: string;
        exists: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createRoom"
  ): TypedContractMethod<
    [name: string, description: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "editMessage"
  ): TypedContractMethod<
    [
      roomId: BigNumberish,
      messageId: BigNumberish,
      newEncryptedContent: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedMessage"
  ): TypedContractMethod<
    [roomId: BigNumberish, messageId: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMessageMetadata"
  ): TypedContractMethod<
    [roomId: BigNumberish, messageId: BigNumberish],
    [
      [string, bigint, boolean, bigint] & {
        sender: string;
        timestamp: bigint;
        edited: boolean;
        editTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoom"
  ): TypedContractMethod<
    [roomId: BigNumberish],
    [
      [string, string, string, bigint] & {
        name: string;
        description: string;
        creator: string;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoomMessageCount"
  ): TypedContractMethod<[roomId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserNickname"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isUserRegistered"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "messages"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, string, bigint, bigint, boolean, bigint] & {
        sender: string;
        roomId: bigint;
        encryptedContent: string;
        timestamp: bigint;
        messageId: bigint;
        edited: boolean;
        editTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<[nickname: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "roomMessageCounts"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "rooms"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, boolean] & {
        name: string;
        description: string;
        creator: string;
        createdAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "sendMessage"
  ): TypedContractMethod<
    [roomId: BigNumberish, encryptedContent: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalMessages"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRooms"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateNickname"
  ): TypedContractMethod<[newNickname: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userProfiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint] & {
        nickname: string;
        exists: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "MessageEdited"
  ): TypedContractEvent<
    MessageEditedEvent.InputTuple,
    MessageEditedEvent.OutputTuple,
    MessageEditedEvent.OutputObject
  >;
  getEvent(
    key: "MessageSent"
  ): TypedContractEvent<
    MessageSentEvent.InputTuple,
    MessageSentEvent.OutputTuple,
    MessageSentEvent.OutputObject
  >;
  getEvent(
    key: "NicknameUpdated"
  ): TypedContractEvent<
    NicknameUpdatedEvent.InputTuple,
    NicknameUpdatedEvent.OutputTuple,
    NicknameUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoomCreated"
  ): TypedContractEvent<
    RoomCreatedEvent.InputTuple,
    RoomCreatedEvent.OutputTuple,
    RoomCreatedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "MessageEdited(uint256,uint256,address,uint256)": TypedContractEvent<
      MessageEditedEvent.InputTuple,
      MessageEditedEvent.OutputTuple,
      MessageEditedEvent.OutputObject
    >;
    MessageEdited: TypedContractEvent<
      MessageEditedEvent.InputTuple,
      MessageEditedEvent.OutputTuple,
      MessageEditedEvent.OutputObject
    >;

    "MessageSent(uint256,uint256,address,uint256)": TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;
    MessageSent: TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;

    "NicknameUpdated(address,string)": TypedContractEvent<
      NicknameUpdatedEvent.InputTuple,
      NicknameUpdatedEvent.OutputTuple,
      NicknameUpdatedEvent.OutputObject
    >;
    NicknameUpdated: TypedContractEvent<
      NicknameUpdatedEvent.InputTuple,
      NicknameUpdatedEvent.OutputTuple,
      NicknameUpdatedEvent.OutputObject
    >;

    "RoomCreated(uint256,string,address)": TypedContractEvent<
      RoomCreatedEvent.InputTuple,
      RoomCreatedEvent.OutputTuple,
      RoomCreatedEvent.OutputObject
    >;
    RoomCreated: TypedContractEvent<
      RoomCreatedEvent.InputTuple,
      RoomCreatedEvent.OutputTuple,
      RoomCreatedEvent.OutputObject
    >;

    "UserRegistered(address,string)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
