/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TicTacToeFHEInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createGame"
      | "gameCounter"
      | "games"
      | "getEncryptedBoard"
      | "getGame"
      | "getPlayerActiveGames"
      | "isWinner"
      | "joinGame"
      | "makeMove"
      | "playerActiveGames"
      | "revealWinner"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GameCreated"
      | "GameEnded"
      | "MoveMade"
      | "PlayerJoined"
      | "WinnerRevealed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createGame",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gameCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "games", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBoard",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerActiveGames",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWinner",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "joinGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "makeMove",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "playerActiveGames",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revealWinner",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "createGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gameCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "games", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBoard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerActiveGames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isWinner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "joinGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "makeMove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playerActiveGames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealWinner",
    data: BytesLike
  ): Result;
}

export namespace GameCreatedEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player1: AddressLike,
    player2: AddressLike
  ];
  export type OutputTuple = [gameId: bigint, player1: string, player2: string];
  export interface OutputObject {
    gameId: bigint;
    player1: string;
    player2: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameEndedEvent {
  export type InputTuple = [gameId: BigNumberish, winner: AddressLike];
  export type OutputTuple = [gameId: bigint, winner: string];
  export interface OutputObject {
    gameId: bigint;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MoveMadeEvent {
  export type InputTuple = [
    gameId: BigNumberish,
    player: AddressLike,
    position: BigNumberish
  ];
  export type OutputTuple = [gameId: bigint, player: string, position: bigint];
  export interface OutputObject {
    gameId: bigint;
    player: string;
    position: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerJoinedEvent {
  export type InputTuple = [gameId: BigNumberish, player2: AddressLike];
  export type OutputTuple = [gameId: bigint, player2: string];
  export interface OutputObject {
    gameId: bigint;
    player2: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerRevealedEvent {
  export type InputTuple = [gameId: BigNumberish, winner: AddressLike];
  export type OutputTuple = [gameId: bigint, winner: string];
  export interface OutputObject {
    gameId: bigint;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TicTacToeFHE extends BaseContract {
  connect(runner?: ContractRunner | null): TicTacToeFHE;
  waitForDeployment(): Promise<this>;

  interface: TicTacToeFHEInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createGame: TypedContractMethod<[], [bigint], "nonpayable">;

  gameCounter: TypedContractMethod<[], [bigint], "view">;

  games: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, boolean, string, bigint, bigint] & {
        player1: string;
        player2: string;
        currentPlayer: string;
        isActive: boolean;
        winner: string;
        createdAt: bigint;
        moveCount: bigint;
      }
    ],
    "view"
  >;

  getEncryptedBoard: TypedContractMethod<
    [gameId: BigNumberish],
    [string[]],
    "view"
  >;

  getGame: TypedContractMethod<
    [gameId: BigNumberish],
    [
      [string, string, string, boolean, string, bigint] & {
        player1: string;
        player2: string;
        currentPlayer: string;
        isActive: boolean;
        winner: string;
        moveCount: bigint;
      }
    ],
    "view"
  >;

  getPlayerActiveGames: TypedContractMethod<
    [player: AddressLike],
    [bigint[]],
    "view"
  >;

  isWinner: TypedContractMethod<
    [gameId: BigNumberish, player: AddressLike],
    [boolean],
    "view"
  >;

  joinGame: TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;

  makeMove: TypedContractMethod<
    [
      gameId: BigNumberish,
      position: BigNumberish,
      encryptedMove: BytesLike,
      attestation: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  playerActiveGames: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  revealWinner: TypedContractMethod<
    [gameId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createGame"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "gameCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "games"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, boolean, string, bigint, bigint] & {
        player1: string;
        player2: string;
        currentPlayer: string;
        isActive: boolean;
        winner: string;
        createdAt: bigint;
        moveCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedBoard"
  ): TypedContractMethod<[gameId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getGame"
  ): TypedContractMethod<
    [gameId: BigNumberish],
    [
      [string, string, string, boolean, string, bigint] & {
        player1: string;
        player2: string;
        currentPlayer: string;
        isActive: boolean;
        winner: string;
        moveCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerActiveGames"
  ): TypedContractMethod<[player: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isWinner"
  ): TypedContractMethod<
    [gameId: BigNumberish, player: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinGame"
  ): TypedContractMethod<[gameId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "makeMove"
  ): TypedContractMethod<
    [
      gameId: BigNumberish,
      position: BigNumberish,
      encryptedMove: BytesLike,
      attestation: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "playerActiveGames"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "revealWinner"
  ): TypedContractMethod<
    [gameId: BigNumberish, winner: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "GameCreated"
  ): TypedContractEvent<
    GameCreatedEvent.InputTuple,
    GameCreatedEvent.OutputTuple,
    GameCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GameEnded"
  ): TypedContractEvent<
    GameEndedEvent.InputTuple,
    GameEndedEvent.OutputTuple,
    GameEndedEvent.OutputObject
  >;
  getEvent(
    key: "MoveMade"
  ): TypedContractEvent<
    MoveMadeEvent.InputTuple,
    MoveMadeEvent.OutputTuple,
    MoveMadeEvent.OutputObject
  >;
  getEvent(
    key: "PlayerJoined"
  ): TypedContractEvent<
    PlayerJoinedEvent.InputTuple,
    PlayerJoinedEvent.OutputTuple,
    PlayerJoinedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerRevealed"
  ): TypedContractEvent<
    WinnerRevealedEvent.InputTuple,
    WinnerRevealedEvent.OutputTuple,
    WinnerRevealedEvent.OutputObject
  >;

  filters: {
    "GameCreated(uint256,address,address)": TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;
    GameCreated: TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;

    "GameEnded(uint256,address)": TypedContractEvent<
      GameEndedEvent.InputTuple,
      GameEndedEvent.OutputTuple,
      GameEndedEvent.OutputObject
    >;
    GameEnded: TypedContractEvent<
      GameEndedEvent.InputTuple,
      GameEndedEvent.OutputTuple,
      GameEndedEvent.OutputObject
    >;

    "MoveMade(uint256,address,uint8)": TypedContractEvent<
      MoveMadeEvent.InputTuple,
      MoveMadeEvent.OutputTuple,
      MoveMadeEvent.OutputObject
    >;
    MoveMade: TypedContractEvent<
      MoveMadeEvent.InputTuple,
      MoveMadeEvent.OutputTuple,
      MoveMadeEvent.OutputObject
    >;

    "PlayerJoined(uint256,address)": TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;
    PlayerJoined: TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;

    "WinnerRevealed(uint256,address)": TypedContractEvent<
      WinnerRevealedEvent.InputTuple,
      WinnerRevealedEvent.OutputTuple,
      WinnerRevealedEvent.OutputObject
    >;
    WinnerRevealed: TypedContractEvent<
      WinnerRevealedEvent.InputTuple,
      WinnerRevealedEvent.OutputTuple,
      WinnerRevealedEvent.OutputObject
    >;
  };
}
